// TOOD: Give every opcode a lhs and rhs addressing mode

use std::{collections::HashMap, ops::Add};

#[derive(Clone)]
pub enum Register {
    A,
    B,
    C,
    D,
    E,
    H,
    L,
    AF,
    BC,
    DE,
    HL,
    SP,
}

#[derive(Clone)]
pub enum AddressingMode {
    ImmediateRegister(Register),
    AddressRegister(Register),
    ImmediateU8,
    AddressHRAM,
    ImmediateI8,
    ImmediateU16,
    AddressU16,
    IoAdressOffset,
    None,
}

pub struct Opcode {
    pub code: u8,
    pub asm: String,
    pub bytes: u8,
    pub t_cycles: u8,
    pub lhs: AddressingMode,
    pub rhs: AddressingMode,
}

impl Opcode {
    pub fn new(
        code: u8,
        asm: String,
        bytes: u8,
        t_cycles: u8,
        lhs: AddressingMode,
        rhs: AddressingMode,
    ) -> Self {
        Opcode {
            code,
            asm,
            bytes,
            t_cycles,
            lhs,
            rhs,
        }
    }

    #[rustfmt::skip]
    pub fn generate_normal_opcode_map() -> HashMap<u8, Opcode> {
        let opcodes: Vec<Opcode> = vec![
            // Misc/Control instructions
            Opcode::new(0x00, "NOP".to_string(), 1, 4, AddressingMode::None, AddressingMode::None),
            Opcode::new(0x10, "STOP n8".to_string(), 2, 4, AddressingMode::ImmediateU8, AddressingMode::None),
            Opcode::new(0x76, "HALT".to_string(), 1, 4, AddressingMode::None, AddressingMode::None),
            Opcode::new(0xf3, "DI".to_string(), 1, 4, AddressingMode::None, AddressingMode::None),
            Opcode::new(0xfb, "EI".to_string(), 1, 4, AddressingMode::None, AddressingMode::None),
            // Jump/Call instructions
            Opcode::new(0x18, "JR, e8".to_string(), 2, 12, AddressingMode::None, AddressingMode::ImmediateI8),
            Opcode::new(0x20, "JR NZ, e8".to_string(), 2, 8 /* + 4 if taken */, AddressingMode::None, AddressingMode::ImmediateI8),
            Opcode::new(0x28, "JR Z, e8".to_string(), 2, 8 /* + 4 if taken */, AddressingMode::None, AddressingMode::ImmediateI8),
            Opcode::new(0xc3, "JP a16".to_string(), 3, 16, AddressingMode::AddressU16, AddressingMode::None),
            Opcode::new(0xc8, "RET Z".to_string(), 1, 8 /* + 12 if taken */, AddressingMode::None, AddressingMode::None),
            Opcode::new(0xc9, "RET".to_string(), 1, 16, AddressingMode::None, AddressingMode::None),
            Opcode::new(0xcd, "CALL a16".to_string(), 3, 24, AddressingMode::AddressU16, AddressingMode::None),
            // 8-bit load instructions
            Opcode::new(0x02, "LD [BC], A".to_string(), 1, 8, AddressingMode::AddressRegister(Register::BC), AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0x06, "LD B, n8".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::B), AddressingMode::ImmediateU8),
            Opcode::new(0x0a, "LD A, [BC]".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::AddressRegister(Register::BC)),
            Opcode::new(0x0e, "LD C, n8".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::C), AddressingMode::ImmediateU8),
            Opcode::new(0x12, "LD [DE], A".to_string(), 1, 8, AddressingMode::AddressRegister(Register::DE), AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0x16, "LD D, n8".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::D), AddressingMode::ImmediateU8),
            Opcode::new(0x1a, "LD A, [DE]".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::AddressRegister(Register::DE)),
            Opcode::new(0x1e, "LD E, n8".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::E), AddressingMode::ImmediateU8),
            Opcode::new(0x22, "LD [HL+], A".to_string(), 1, 8, AddressingMode::AddressRegister(Register::HL), AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0x26, "LD H, n8".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::H), AddressingMode::ImmediateU8),
            Opcode::new(0x2a, "LD A, [HL+]".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::AddressRegister(Register::HL)),
            Opcode::new(0x2e, "LD L, n8".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::L), AddressingMode::ImmediateU8),
            Opcode::new(0x32, "LD [HL-], A".to_string(), 1, 8, AddressingMode::AddressRegister(Register::HL), AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0x36, "LD [HL], n8".to_string(), 2, 12, AddressingMode::AddressRegister(Register::HL), AddressingMode::ImmediateU8),
            Opcode::new(0x3a, "LD A, [HL-]".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::AddressRegister(Register::HL)),
            Opcode::new(0x3e, "LD A, n8".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateU8,),
            Opcode::new(0x40, "LD B, B".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::B), AddressingMode::ImmediateRegister(Register::B)),
            Opcode::new(0x41, "LD B, C".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::B), AddressingMode::ImmediateRegister(Register::C)),
            Opcode::new(0x42, "LD B, D".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::B), AddressingMode::ImmediateRegister(Register::D)),
            Opcode::new(0x43, "LD B, E".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::B), AddressingMode::ImmediateRegister(Register::E)),
            Opcode::new(0x44, "LD B, H".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::B), AddressingMode::ImmediateRegister(Register::H)),
            Opcode::new(0x45, "LD B, L".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::B), AddressingMode::ImmediateRegister(Register::L)),
            Opcode::new(0x46, "LD B, [HL]".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::B), AddressingMode::AddressRegister(Register::HL)),
            Opcode::new(0x47, "LD B, A".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::B), AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0x48, "LD C, B".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::C), AddressingMode::ImmediateRegister(Register::B)),
            Opcode::new(0x49, "LD C, C".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::C), AddressingMode::ImmediateRegister(Register::C)),
            Opcode::new(0x4a, "LD C, D".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::C), AddressingMode::ImmediateRegister(Register::D)),
            Opcode::new(0x4b, "LD C, E".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::C), AddressingMode::ImmediateRegister(Register::E)),
            Opcode::new(0x4c, "LD C, H".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::C), AddressingMode::ImmediateRegister(Register::H)),
            Opcode::new(0x4d, "LD C, L".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::C), AddressingMode::ImmediateRegister(Register::L)),
            Opcode::new(0x4e, "LD C, [HL]".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::C), AddressingMode::AddressRegister(Register::HL)),
            Opcode::new(0x4f, "LD C, A".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::C), AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0x50, "LD D, B".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::D), AddressingMode::ImmediateRegister(Register::B)),
            Opcode::new(0x51, "LD D, C".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::D), AddressingMode::ImmediateRegister(Register::C)),
            Opcode::new(0x52, "LD D, D".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::D), AddressingMode::ImmediateRegister(Register::D)),
            Opcode::new(0x53, "LD D, E".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::D), AddressingMode::ImmediateRegister(Register::E)),
            Opcode::new(0x54, "LD D, H".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::D), AddressingMode::ImmediateRegister(Register::H)),
            Opcode::new(0x55, "LD D, L".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::D), AddressingMode::ImmediateRegister(Register::L)),
            Opcode::new(0x56, "LD D, [HL]".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::D), AddressingMode::AddressRegister(Register::HL)),
            Opcode::new(0x57, "LD D, A".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::D), AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0x58, "LD E, B".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::E), AddressingMode::ImmediateRegister(Register::B)),
            Opcode::new(0x59, "LD E, C".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::E), AddressingMode::ImmediateRegister(Register::C)),
            Opcode::new(0x5a, "LD E, D".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::E), AddressingMode::ImmediateRegister(Register::D)),
            Opcode::new(0x5b, "LD E, E".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::E), AddressingMode::ImmediateRegister(Register::E)),
            Opcode::new(0x5c, "LD E, H".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::E), AddressingMode::ImmediateRegister(Register::H)),
            Opcode::new(0x5d, "LD E, L".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::E), AddressingMode::ImmediateRegister(Register::L)),
            Opcode::new(0x5e, "LD E, [HL]".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::E), AddressingMode::AddressRegister(Register::HL)),
            Opcode::new(0x5f, "LD E, A".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::E), AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0x60, "LD H, B".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::H), AddressingMode::ImmediateRegister(Register::B)),
            Opcode::new(0x61, "LD H, C".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::H), AddressingMode::ImmediateRegister(Register::C)),
            Opcode::new(0x62, "LD H, D".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::H), AddressingMode::ImmediateRegister(Register::D)),
            Opcode::new(0x63, "LD H, E".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::H), AddressingMode::ImmediateRegister(Register::E)),
            Opcode::new(0x64, "LD H, H".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::H), AddressingMode::ImmediateRegister(Register::H)),
            Opcode::new(0x65, "LD H, L".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::H), AddressingMode::ImmediateRegister(Register::L)),
            Opcode::new(0x66, "LD H, [HL]".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::H), AddressingMode::AddressRegister(Register::HL)),
            Opcode::new(0x67, "LD H, A".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::H), AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0x68, "LD L, B".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::L), AddressingMode::ImmediateRegister(Register::B)),
            Opcode::new(0x69, "LD L, C".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::L), AddressingMode::ImmediateRegister(Register::C)),
            Opcode::new(0x6a, "LD L, D".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::L), AddressingMode::ImmediateRegister(Register::D)),
            Opcode::new(0x6b, "LD L, E".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::L), AddressingMode::ImmediateRegister(Register::E)),
            Opcode::new(0x6c, "LD L, H".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::L), AddressingMode::ImmediateRegister(Register::H)),
            Opcode::new(0x6d, "LD L, L".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::L), AddressingMode::ImmediateRegister(Register::L)),
            Opcode::new(0x6e, "LD L, [HL]".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::L), AddressingMode::AddressRegister(Register::HL)),
            Opcode::new(0x6f, "LD L, A".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::L), AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0x70, "LD [HL], B".to_string(), 1, 8, AddressingMode::AddressRegister(Register::HL), AddressingMode::ImmediateRegister(Register::B)),
            Opcode::new(0x71, "LD [HL], C".to_string(), 1, 8, AddressingMode::AddressRegister(Register::HL), AddressingMode::ImmediateRegister(Register::C)),
            Opcode::new(0x72, "LD [HL], D".to_string(), 1, 8, AddressingMode::AddressRegister(Register::HL), AddressingMode::ImmediateRegister(Register::D)),
            Opcode::new(0x73, "LD [HL], E".to_string(), 1, 8, AddressingMode::AddressRegister(Register::HL), AddressingMode::ImmediateRegister(Register::E)),
            Opcode::new(0x74, "LD [HL], H".to_string(), 1, 8, AddressingMode::AddressRegister(Register::HL), AddressingMode::ImmediateRegister(Register::H)),
            Opcode::new(0x75, "LD [HL], L".to_string(), 1, 8, AddressingMode::AddressRegister(Register::HL), AddressingMode::ImmediateRegister(Register::L)),
            Opcode::new(0x77, "LD [HL], A".to_string(), 1, 8, AddressingMode::AddressRegister(Register::HL), AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0x78, "LD A, B".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::B)),
            Opcode::new(0x79, "LD A, C".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::C)),
            Opcode::new(0x7a, "LD A, D".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::D)),
            Opcode::new(0x7b, "LD A, E".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::E)),
            Opcode::new(0x7c, "LD A, H".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::H)),
            Opcode::new(0x7d, "LD A, L".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::L)),
            Opcode::new(0x7e, "LD A, [HL]".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::AddressRegister(Register::HL)),
            Opcode::new(0x7f, "LD A, A".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0xe0, "LDH [a8], A".to_string(), 2, 12, AddressingMode::AddressHRAM, AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0xe2, "LD [C], A".to_string(), 1, 8, AddressingMode::IoAdressOffset, AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0xea, "LD [a16], A".to_string(), 3, 16, AddressingMode::AddressU16, AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0xf0, "LDH A, [a8]".to_string(), 2, 12, AddressingMode::ImmediateRegister(Register::A), AddressingMode::AddressHRAM),
            Opcode::new(0x77, "LD [HL], A".to_string(), 1, 8, AddressingMode::AddressRegister(Register::HL), AddressingMode::ImmediateRegister(Register::A),),
            // 16-bit load instructions
            Opcode::new(0x01, "LD BC, n16".to_string(), 3, 12, AddressingMode::ImmediateRegister(Register::BC), AddressingMode::ImmediateU16),
            Opcode::new(0x08, "LD [a16], SP".to_string(), 3, 20, AddressingMode::AddressU16, AddressingMode::ImmediateRegister(Register::SP)),
            Opcode::new(0x11, "LD DE, n16".to_string(), 3, 12, AddressingMode::ImmediateRegister(Register::DE), AddressingMode::ImmediateU16),
            Opcode::new(0x21, "LD HL, n16".to_string(), 3, 12, AddressingMode::ImmediateRegister(Register::HL), AddressingMode::ImmediateU16),
            Opcode::new(0x31, "LD SP, n16".to_string(), 3, 12, AddressingMode::ImmediateRegister(Register::SP), AddressingMode::ImmediateU16),
            Opcode::new(0xc1, "POP BC".to_string(), 1, 16, AddressingMode::ImmediateRegister(Register::BC), AddressingMode::None),
            Opcode::new(0xc5, "PUSH BC".to_string(), 1, 16, AddressingMode::ImmediateRegister(Register::BC), AddressingMode::None),
            // 8-bit arithmetic/logical instructions
            Opcode::new(0x04, "INC B".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::B), AddressingMode::None),
            Opcode::new(0x05, "DEC B".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::B), AddressingMode::None),
            Opcode::new(0x0c, "INC C".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::C), AddressingMode::None),
            Opcode::new(0x0d, "DEC C".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::C), AddressingMode::None),
            Opcode::new(0x14, "INC D".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::D), AddressingMode::None),
            Opcode::new(0x15, "DEC D".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::D), AddressingMode::None),
            Opcode::new(0x1c, "INC E".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::E), AddressingMode::None),
            Opcode::new(0x1d, "DEC E".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::E), AddressingMode::None),
            Opcode::new(0x24, "INC H".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::H), AddressingMode::None),
            Opcode::new(0x25, "DEC H".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::H), AddressingMode::None),
            Opcode::new(0x27, "DAA".to_string(), 1, 4, AddressingMode::None, AddressingMode::None),
            Opcode::new(0x2c, "INC L".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::L), AddressingMode::None),
            Opcode::new(0x2d, "DEC L".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::L), AddressingMode::None),
            Opcode::new(0x2f, "CPL".to_string(), 1, 4, AddressingMode::None, AddressingMode::None),
            Opcode::new(0x34, "INC [HL]".to_string(), 1, 12, AddressingMode::AddressRegister(Register::HL), AddressingMode::None),
            Opcode::new(0x35, "DEC [HL]".to_string(), 1, 12, AddressingMode::AddressRegister(Register::HL), AddressingMode::None),
            Opcode::new(0x37, "SCF".to_string(), 1, 4, AddressingMode::None, AddressingMode::None),
            Opcode::new(0x3c, "INC A".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::None),
            Opcode::new(0x3d, "DEC A".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::None),
            Opcode::new(0x3f, "CCF".to_string(), 1, 4, AddressingMode::None, AddressingMode::None),
            Opcode::new(0x80, "ADD A, B".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::B)),
            Opcode::new(0x81, "ADD A, C".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::C)),
            Opcode::new(0x82, "ADD A, D".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::D)),
            Opcode::new(0x83, "ADD A, E".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::E)),
            Opcode::new(0x84, "ADD A, H".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::H)),
            Opcode::new(0x85, "ADD A, L".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::L)),
            Opcode::new(0x86, "ADD A, [HL]".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::AddressRegister(Register::HL)),
            Opcode::new(0x87, "ADD A, A".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0x88, "ADC A, B".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::B)),
            Opcode::new(0x89, "ADC A, C".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::C)),
            Opcode::new(0x8a, "ADC A, D".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::D)),
            Opcode::new(0x8b, "ADC A, E".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::E)),
            Opcode::new(0x8c, "ADC A, H".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::H)),
            Opcode::new(0x8d, "ADC A, L".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::L)),
            Opcode::new(0x8e, "ADC A, [HL]".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::AddressRegister(Register::HL)),
            Opcode::new(0x8f, "ADC A, A".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0x90, "SUB A, B".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::B)),
            Opcode::new(0x91, "SUB A, C".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::C)),
            Opcode::new(0x92, "SUB A, D".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::D)),
            Opcode::new(0x93, "SUB A, E".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::E)),
            Opcode::new(0x94, "SUB A, H".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::H)),
            Opcode::new(0x95, "SUB A, L".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::L)),
            Opcode::new(0x96, "SUB A, [HL]".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::AddressRegister(Register::HL)),
            Opcode::new(0x97, "SUB A, A".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0x98, "SBC A, B".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::B)),
            Opcode::new(0x99, "SBC A, C".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::C)),
            Opcode::new(0x9a, "SBC A, D".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::D)),
            Opcode::new(0x9b, "SBC A, E".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::E)),
            Opcode::new(0x9c, "SBC A, H".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::H)),
            Opcode::new(0x9d, "SBC A, L".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::L)),
            Opcode::new(0x9e, "SBC A, [HL]".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::AddressRegister(Register::HL)),
            Opcode::new(0x9f, "SBC A, A".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0xa0, "AND A, B".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::B)),
            Opcode::new(0xa1, "AND A, C".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::C)),
            Opcode::new(0xa2, "AND A, D".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::D)),
            Opcode::new(0xa3, "AND A, E".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::E)),
            Opcode::new(0xa4, "AND A, H".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::H)),
            Opcode::new(0xa5, "AND A, L".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::L)),
            Opcode::new(0xa6, "AND A, [HL]".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::AddressRegister(Register::HL)),
            Opcode::new(0xa7, "AND A, A".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0xa8, "XOR A, B".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::B)),
            Opcode::new(0xa9, "XOR A, C".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::C)),
            Opcode::new(0xaa, "XOR A, D".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::D)),
            Opcode::new(0xab, "XOR A, E".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::E)),
            Opcode::new(0xac, "XOR A, H".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::H)),
            Opcode::new(0xad, "XOR A, L".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::L)),
            Opcode::new(0xae, "XOR A, [HL]".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::AddressRegister(Register::HL)),
            Opcode::new(0xaf, "XOR A, A".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0xb0, "OR A, B".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::B)),
            Opcode::new(0xb1, "OR A, C".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::C)),
            Opcode::new(0xb2, "OR A, D".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::D)),
            Opcode::new(0xb3, "OR A, E".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::E)),
            Opcode::new(0xb4, "OR A, H".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::H)),
            Opcode::new(0xb5, "OR A, L".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::L)),
            Opcode::new(0xb6, "OR A, [HL]".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::AddressRegister(Register::HL)),
            Opcode::new(0xb7, "OR A, A".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0xb8, "CP A, B".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::B)),
            Opcode::new(0xb9, "CP A, C".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::C)),
            Opcode::new(0xba, "CP A, D".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::D)),
            Opcode::new(0xbb, "CP A, E".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::E)),
            Opcode::new(0xbc, "CP A, H".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::H)),
            Opcode::new(0xbd, "CP A, L".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::L)),
            Opcode::new(0xbe, "CP A, [HL]".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::AddressRegister(Register::HL)),
            Opcode::new(0xbf, "CP A, A".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateRegister(Register::A)),
            Opcode::new(0xc6, "ADD A, n8".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateU8),
            Opcode::new(0xce, "ADC A, n8".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateU8),
            Opcode::new(0xd6, "SUB A, n8".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateU8),
            Opcode::new(0xde, "SBC A, n8".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateU8),
            Opcode::new(0xe6, "AND A, n8".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateU8),
            Opcode::new(0xee, "XOR A, n8".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateU8),
            Opcode::new(0xf6, "OR A, n8".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateU8),
            Opcode::new(0xfe, "CP A, n8".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::ImmediateU8),
            // 16-bit arithmetic/logical instructions
            Opcode::new(0x03, "INC BC".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::BC), AddressingMode::None),
            Opcode::new(0x09, "ADD HL, BC".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::HL), AddressingMode::ImmediateRegister(Register::BC)),
            Opcode::new(0x0b, "DEC BC".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::BC), AddressingMode::None),
            Opcode::new(0x13, "INC DE".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::DE), AddressingMode::None),
            Opcode::new(0x19, "ADD HL, DE".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::HL), AddressingMode::ImmediateRegister(Register::DE)),
            Opcode::new(0x1b, "DEC DE".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::DE), AddressingMode::None),
            Opcode::new(0x23, "INC HL".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::HL), AddressingMode::None),
            Opcode::new(0x29, "ADD HL, HL".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::HL), AddressingMode::ImmediateRegister(Register::HL)),
            Opcode::new(0x2b, "DEC HL".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::HL), AddressingMode::None),
            Opcode::new(0x33, "INC SP".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::SP), AddressingMode::None),
            Opcode::new(0x39, "ADD HL, SP".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::HL), AddressingMode::ImmediateRegister(Register::SP)),
            Opcode::new(0x3b, "DEC SP".to_string(), 1, 8, AddressingMode::ImmediateRegister(Register::SP), AddressingMode::None),
            Opcode::new(0xe8, "ADD SP, e8".to_string(), 2, 16, AddressingMode::ImmediateRegister(Register::SP), AddressingMode::ImmediateI8),
            // 8-bit shift, rotate and bit instructions
            Opcode::new(0x07, "RLCA".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::None),
            Opcode::new(0x17, "RLA".to_string(), 1, 4, AddressingMode::ImmediateRegister(Register::A), AddressingMode::None),
        ];

        let mut map = HashMap::new();
        for op in opcodes {
            map.insert(op.code, op);
        }
        map
    }

    #[rustfmt::skip]
    pub fn generate_prefixed_opcode_map() -> HashMap<u8, Opcode> {
        let opcodes: Vec<Opcode> = vec![
            Opcode::new(0x00, "RLC B".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::B), AddressingMode::None),
            Opcode::new(0x01, "RLC C".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::C), AddressingMode::None),
            Opcode::new(0x02, "RLC D".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::D), AddressingMode::None),
            Opcode::new(0x03, "RLC E".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::E), AddressingMode::None),
            Opcode::new(0x04, "RLC H".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::H), AddressingMode::None),
            Opcode::new(0x05, "RLC L".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::L), AddressingMode::None),
            Opcode::new(0x06, "RLC [HL]".to_string(), 2, 16, AddressingMode::AddressRegister(Register::HL), AddressingMode::None),
            Opcode::new(0x07, "RLC A".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::None),
            Opcode::new(0x08, "RRC B".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::B), AddressingMode::None),
            Opcode::new(0x09, "RRC C".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::C), AddressingMode::None),
            Opcode::new(0x0a, "RRC D".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::D), AddressingMode::None),
            Opcode::new(0x0b, "RRC E".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::E), AddressingMode::None),
            Opcode::new(0x0c, "RRC H".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::H), AddressingMode::None),
            Opcode::new(0x0d, "RRC L".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::L), AddressingMode::None),
            Opcode::new(0x0e, "RRC [HL]".to_string(), 2, 16, AddressingMode::AddressRegister(Register::HL), AddressingMode::None),
            Opcode::new(0x0f, "RRC A".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::None),
            Opcode::new(0x10, "RL B".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::B), AddressingMode::None),
            Opcode::new(0x11, "RL C".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::C), AddressingMode::None),
            Opcode::new(0x12, "RL D".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::D), AddressingMode::None),
            Opcode::new(0x13, "RL E".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::E), AddressingMode::None),
            Opcode::new(0x14, "RL H".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::H), AddressingMode::None),
            Opcode::new(0x15, "RL L".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::L), AddressingMode::None),
            Opcode::new(0x16, "RL [HL]".to_string(), 2, 16, AddressingMode::AddressRegister(Register::HL), AddressingMode::None),
            Opcode::new(0x17, "RL A".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::None),
            Opcode::new(0x18, "RR B".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::B), AddressingMode::None),
            Opcode::new(0x19, "RR C".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::C), AddressingMode::None),
            Opcode::new(0x1a, "RR D".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::D), AddressingMode::None),
            Opcode::new(0x1b, "RR E".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::E), AddressingMode::None),
            Opcode::new(0x1c, "RR H".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::H), AddressingMode::None),
            Opcode::new(0x1d, "RR L".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::L), AddressingMode::None),
            Opcode::new(0x1e, "RR [HL]".to_string(), 2, 16, AddressingMode::AddressRegister(Register::HL), AddressingMode::None),
            Opcode::new(0x1f, "RR A".to_string(), 2, 8, AddressingMode::ImmediateRegister(Register::A), AddressingMode::None),
            Opcode::new(0xbe, "RES 7, [HL]".to_string(), 2, 16, AddressingMode::None, AddressingMode::AddressRegister(Register::HL)),
            Opcode::new(0x7c, "BIT 7, H".to_string(), 2, 8, AddressingMode::None, AddressingMode::ImmediateRegister(Register::H)),
            Opcode::new(0x7e, "BIT 7, [HL]".to_string(), 2, 12, AddressingMode::None, AddressingMode::AddressRegister(Register::HL)),
        ];

        let mut map = HashMap::new();
        for op in opcodes {
            map.insert(op.code, op);
        }
        map
    }
}
